name: Deploy Frontend

on:
  push:
    branches:
      - frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH key for Bastion Host
      - name: Set up SSH key for Bastion Host
        env:
          BASTION_PRIVATE_KEY: ${{ secrets.BASTION_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$BASTION_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host bastion\n  HostName ${{ secrets.BASTION_HOST }}\n  User ${{ secrets.BASTION_USER }}\n  IdentityFile ~/.ssh/id_rsa" > ~/.ssh/config
          ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts

      # Step 3: Set up the SSH command for accessing the private instance via the bastion host
      - name: Deploy Frontend to OVHcloud via Bastion Host
        env:
          PRIVATE_INSTANCE_IP: ${{ secrets.PRIVATE_INSTANCE_IP }}
          PRIVATE_INSTANCE_USER: ${{ secrets.PRIVATE_INSTANCE_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -J ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} \
            ${{ secrets.PRIVATE_INSTANCE_USER }}@$PRIVATE_INSTANCE_IP <<EOF
          sudo apt update
          sudo apt install -y nginx
          sudo rm -rf /var/www/html/*
          sudo mkdir -p /var/www/html
          sudo bash -c 'cat > /var/www/html/index.html << "EOL"
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Frontend App</title>
          </head>
          <body>
              <h1>Welcome to the Frontend, Francis K.!</h1>
              <p>This is served from OVHcloud.</p>
              <p>Below is a 2025 WRX S4!!!</p>
              <img src="https://franc-s3-ovh-bucket.s3.us-east-va.io.cloud.ovh.us/subaru-wrx-s4-sti-performance-concept.jpg" alt="Subaru WRX S4 STI Performance Concept" style="max-width:100%;height:auto;">
          </body>
          </html>
          EOL'
          sudo systemctl restart nginx
          EOF

      # Step 4: Cleanup
      - name: Cleanup
        run: |
          rm -rf ~/.ssh/id_rsa ~/.ssh/config
